name: Ruff Formatting

on: push

jobs:
  formatting-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11.1

      - name: Code Formatting (App)
        run: |
          pip install -r requirements-dev.txt
          ruff format --check .
